---
- hosts: serverscript
  become: True
  tasks:
        - name: update system
          apt:
            update_cache: yes
            cache_valid_time: 3600
        - name: add ppa
          apt_repository:
            validate_certs: no
            repo: 'ppa:ondrej/php'
            state: present
        - name: install php
          apt:
            pkg:
            - php8.1-bcmath
            - php8.1-cli
            - php8.1-common
            - php8.1-curl
            - php8.1-gd
            - php8.1-imap
            - php8.1-intl
            - php8.1-mbstring
            - php8.1-mysql
            - php8.1-readline
            - php8.1-soap
            - php8.1-xml
            - php8.1-xmlrpc
            - php8.1-zip

        - name: Download and install Composer
          shell: curl -sS https://getcomposer.org/installer | php
          args:
            chdir: /usr/src/
            creates: /usr/local/bin/composer
            warn: false
          become: yes

        - name: Add Composer to global path
          copy:
              dest: /usr/local/bin/composer
              group: root
              mode: '0755'
              owner: root
              src: /usr/src/composer.phar
              remote_src: yes
          become: yes
