- hosts: serverscript
  become: True
  tasks:
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/{{ domain }}/

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
