- hosts: serverscript
  become: True
  tasks:

    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/

    - name: open firewall
      community.general.ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted


