---
- hosts: serverscript
  become: True
  tasks:
        - name: update system
          apt:
            update_cache: yes
            cache_valid_time: 3600
        - name: Download WP-CLI
          shell: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

        - name: Make WP-CLI executable
          file:
            path: /home/azureuser/wp-cli.phar
            mode: u=rwx,g=rx,o=rx

        - name: Move WP-CLI to /usr/local/bin/wp
          command: mv /home/azureuser/wp-cli.phar /usr/local/bin/wp
